syntax = "proto3";

option csharp_namespace = "Contracts.Grpc.Identity";

package identity;

service IdentityGrpc {
  rpc UserExists (UserExistsRequest) returns (UserExistsResponse);
  rpc GetUser (GetUserRequest) returns (GetUserResponse);
}

message UserExistsRequest {
  string userId = 1;
}

message UserExistsResponse {
  bool exists = 1;
}

message GetUserRequest {
  string userId = 1;
}

message GetUserResponse {
  string id = 1;
  string fullName = 2;
  string mobile = 3;
  bool isActive = 4;
}
